"use client";

import { useEffect, useState } from "react";
import { apiFetch, unwrap } from "@/lib/api";

const GROUPS = [["Shirt", [["shirt_body_length", "Body Length"], ["shirt_shoulder", "Shoulder"], ["shirt_sleeve_length", "Sleeve Length"], ["shirt_arm_loose", "Arm Loose"], ["shirt_chest", "Chest"], ["shirt_waist", "Waist"], ["shirt_hip", "Hip"], ["shirt_collar", "Collar"], ["shirt_cuff", "Cuff"]]], ["Trouser", [["trouser_full_length", "Full Length"], ["trouser_inseam", "Inseam"], ["trouser_fly", "Fly"], ["trouser_u_round", "U Round"], ["trouser_waist", "Waist"], ["trouser_hip", "Hip"], ["trouser_thigh", "Thigh"], ["trouser_knee", "Knee"], ["trouser_bottom", "Bottom"]]]];

export default function AdminMeasurementsPage() {
  const [rows, setRows] = useState([]); const [selected, setSelected] = useState(null); const [message, setMessage] = useState("");
  const load = () => apiFetch("/Measurements").then(unwrap).then((v) => setRows(Array.isArray(v) ? v : [])).catch(() => setMessage("Could not load measurements."));
  useEffect(() => { load(); }, []);
  return <div><p className="eyebrow text-gold-deep">Harry Clinton</p><h1 className="mt-1 font-display text-3xl font-bold">Customer Measurements</h1><p className="mt-1 text-sm text-neutral-500">View saved shirt and trouser measurements for every customer.</p>{message && <p className="mt-3 text-sm text-red-700">{message}</p>}<div className="mt-5 overflow-x-auto border border-neutral-200 bg-white shadow-sm"><table className="w-full text-left text-sm"><thead className="bg-[#17161a] text-xs uppercase text-white"><tr><th className="p-3">Customer</th><th className="p-3">Email</th><th className="p-3">Product</th><th className="p-3">Unit</th><th className="p-3">Updated</th><th className="p-3" /></tr></thead><tbody>{rows.map((r) => <tr key={r.measurement_id} className="border-b"><td className="p-3 font-medium">{r.guest_name || r.full_name || "—"}</td><td className="p-3">{r.email || "—"}</td><td className="p-3">{r.product_name || "—"}</td><td className="p-3">{r.unit}</td><td className="p-3">{r.lcm ? new Date(r.lcm).toLocaleDateString("en-IN") : "—"}</td><td className="p-3"><button className="underline" onClick={() => setSelected(r)}>View</button></td></tr>)}{rows.length === 0 && <tr><td colSpan="6" className="p-6 text-center text-neutral-500">No measurements saved yet.</td></tr>}</tbody></table></div>{selected && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4" onClick={() => setSelected(null)}><div className="max-h-[90vh] w-full max-w-3xl overflow-y-auto bg-white p-6" onClick={(e) => e.stopPropagation()}><div className="flex justify-between"><h2 className="font-display text-2xl font-bold">{selected.guest_name || selected.full_name || "Customer"}</h2><button onClick={() => setSelected(null)}>×</button></div><p className="text-sm text-neutral-500">{selected.email} · {selected.unit}</p><div className="mt-5 grid gap-5 md:grid-cols-2">{GROUPS.map(([title, fields]) => <div key={title} className="border border-neutral-200"><h3 className="bg-black p-2 text-center text-sm uppercase text-white">{title}</h3>{fields.map(([key, label]) => <div className="grid grid-cols-2 border-t border-neutral-200 p-2 text-sm" key={key}><span>{label}</span><strong>{selected[key] || "—"}</strong></div>)}</div>)}</div>{selected.notes && <p className="mt-5 text-sm"><strong>Notes:</strong> {selected.notes}</p>}</div></div>}</div>;
}
