"use client";

import { useRouter } from "next/navigation";

const HOW = [
  ["01.", "🤝", "We Collaborate", "We open creative sessions with visually impaired artists through art sessions, conversations, sketches and tactile exploration."],
  ["02.", "✏️", "They Create", "Artists express their imagination through drawings, textures, patterns and emotional storytelling."],
  ["03.", "👕", "We Transform", "Their original artwork is carefully adapted into functional print designs while preserving the soul of the artist's idea."],
  ["04.", "🛍️", "You Wear the Story", "Each piece becomes a wearable reminder that creativity has no limits."],
];

export default function TheVisionLanding() {
  const router = useRouter();
  const scroll = (id) => document.getElementById(id)?.scrollIntoView({ behavior: "smooth" });
  return <>
    <section className="tv-hero"><div className="tv-hero__img-col"><img src="/service-media/vision1.jpeg" alt="The Vision" className="tv-hero__img" /></div><div className="tv-hero__text-col"><p className="tv-hero__presents">HC Presents</p><h1 className="tv-hero__title">THE VISION</h1><p className="tv-hero__subtitle">Beyond Sight.</p><div className="tv-hero__divider" /><p className="tv-hero__tagline">Not every vision begins with sight.</p><p className="tv-hero__desc">A collection created with visually impaired artists who imagine, interpret and express the world in their own unique way.</p><p className="tv-hero__sub-desc">Their art. Their story. Your style.</p><div className="tv-hero__icons">{[["👁️", "Their Imagination Our Prints"], ["👕", "Their Perspective Your Style"], ["❤️", "Every Purchase Creates Impact"]].map(([symbol, label]) => <div className="tv-hero__icon-item" key={label}><span className="tv-hero__icon-symbol">{symbol}</span><span className="tv-hero__icon-label">{label}</span></div>)}</div><div className="tv-hero__btns"><button className="tv-btn" onClick={() => scroll("tv-collection")}>Explore Collection</button><button className="tv-btn tv-btn--outline" onClick={() => scroll("tv-artists")}>Meet the Artists →</button></div><p style={{ marginTop: "3rem", fontSize: "9px", letterSpacing: ".22em", textTransform: "uppercase", color: "rgba(255,255,255,.3)" }}>Wear more than fashion. Wear a different way of seeing.</p></div></section>
    <section className="tv-about"><div className="tv-about__img-wrap"><img src="/service-media/vision_title.jpeg" alt="About The Vision" className="tv-about__img" /></div><div className="tv-about__body"><p className="tv-about__eyebrow">About the Vision</p><h2 className="tv-about__title">Vision is not limited<br />to what the eyes can see.</h2><p className="tv-about__para">For this collection, HC collaborated with visually impaired creators to understand how they imagine the world through touch, sound, memory, emotion, and personal experience.</p><p className="tv-about__para">Their drawings, sketches, textures, and creative interpretations were transformed into original print designs — turning unseen perspectives into fashion that can be worn, felt, and shared.</p><p className="tv-about__highlight">This is more than a collection.<br />It is a celebration of imagination beyond sight.</p></div></section>
    <section className="tv-how"><p className="tv-how__header">How it Works</p><div className="tv-how__steps">{HOW.map(([num, icon, title, desc]) => <div className="tv-how__step" key={num}><span className="tv-how__step-num">{num}</span><span className="tv-how__step-icon">{icon}</span><p className="tv-how__step-title">{title}</p><p className="tv-how__step-desc">{desc}</p></div>)}</div></section>
    <section className="tv-feature" id="tv-collection"><div className="tv-feature__img-wrap"><img src="/service-media/LabelNew2.jpeg" alt="Wear Their Perspective" className="tv-feature__img" /></div><div className="tv-feature__body"><p className="tv-feature__eyebrow">Featured Collection</p><h2 className="tv-feature__title">Wear Their Perspective.</h2><p className="tv-feature__desc">A collection of shirts, jackets, co-ords, and statement pieces inspired by original artwork from visually impaired creators.</p><ul className="tv-feature__list">{["Artist name", "Artwork title", "Story behind the print", "Impact created through purchase"].map((item) => <li key={item}>{item}</li>)}</ul><button className="tv-btn tv-btn--dark" onClick={() => router.push("/new-arrivals")}>Shop the Collection</button></div></section>
    <section className="tv-impact"><p className="tv-impact__eyebrow">Impact</p><h2 className="tv-impact__title">Every Purchase Creates Opportunity.</h2><p className="tv-impact__desc">Every purchase supports creative opportunities for visually impaired artists through fair collaboration, recognition, and continued artistic engagement.</p><div className="tv-impact__pillars">{[["🤝", "Fair Collaboration", "Artists are compensated fairly and credited for every piece produced."], ["🏅", "Artistic Recognition", "Their names and stories are shared with every customer who buys."], ["🎨", "Creative Engagement", "Ongoing workshops keep artists connected, growing and creating."]].map(([icon, title, desc]) => <div key={title}><span className="tv-impact__pillar-icon">{icon}</span><p className="tv-impact__pillar-title">{title}</p><p className="tv-impact__pillar-desc">{desc}</p></div>)}</div><p className="tv-impact__note">This is not charity. It is partnership.<br />It is fashion built with respect, creativity, and shared purpose.<br /><br />Wear the art. Share the impact.</p></section>
    <section className="tv-quote" id="tv-artists"><div><p className="tv-quote__eyebrow">Artist Stories</p><span className="tv-quote__mark">&quot;</span><p className="tv-quote__text">I don&apos;t draw what I see.<br />I draw what I feel.</p><p className="tv-quote__author">— Artist behind the collection</p></div><div className="tv-quote__body"><p className="tv-quote__sub">Meet the creators behind the collection. Discover the memories, emotions, sounds, and textures that shaped every print.</p><button className="tv-btn tv-btn--dark">Meet the Artists →</button></div></section>
    <section className="tv-footer-strip"><h2 className="tv-footer-strip__title"><span>Beyond Sight.</span> <span>Beyond Fashion.</span></h2><div className="tv-footer-strip__pillars">{[["👁️", "The Vision is an invitation\nto see differently."], ["❤️", "To wear something\nmeaningful."], ["🎨", "To celebrate creativity\nwith them."], ["✨", "To turn imagination\ninto impact."]].map(([icon, label]) => <div key={label}><span className="tv-footer-strip__pillar-icon">{icon}</span><p className="tv-footer-strip__pillar-label">{label.split("\n").map((line) => <span key={line}>{line}<br /></span>)}</p></div>)}</div><p className="tv-footer-strip__tagline">Their imagination. Our prints. Your style.</p><button className="tv-btn" onClick={() => router.push("/new-arrivals")}>Explore Collection</button></section>
  </>;
}
